# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160811_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogarticle',
            old_name='is_puplished',
            new_name='is_published',
        ),
    ]
